source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'STXInsider' do

pod 'Alamofire', '~> 3.3.0'

end

target 'STXInsiderTests' do

end

target 'STXInsiderUITests' do

end

